# Part One

You come across a field of hydrothermal vents on the ocean floor! These vents constantly produce large, opaque clouds, so it would be best to avoid them if possible.

They tend to form in lines; the submarine helpfully produces a list of nearby lines of vents (your puzzle input) for you to review. For example:

```
0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2
```

Each line of vents is given as a line segment in the format x1,y1 -> x2,y2 where x1,y1 are the coordinates of one end the line segment and x2,y2 are the coordinates of the other end. These line segments include the points at both ends. In other words:

An entry like 1,1 -> 1,3 covers points 1,1, 1,2, and 1,3.
An entry like 9,7 -> 7,7 covers points 9,7, 8,7, and 7,7.
For now, only consider horizontal and vertical lines: lines where either x1 = x2 or y1 = y2.

So, the horizontal and vertical lines from the above list would produce the following diagram:

```
.......1..
..1....1..
..1....1..
.......1..
.112111211
..........
..........
..........
..........
222111....
```

In this diagram, the top left corner is 0,0 and the bottom right corner is 9,9. Each position is shown as the number of lines which cover that point or . if no line covers that point. The top-left pair of 1s, for example, comes from 2,2 -> 2,1; the very bottom row is formed by the overlapping lines 0,9 -> 5,9 and 0,9 -> 2,9.

To avoid the most dangerous areas, you need to determine the number of points where at least two lines overlap. In the above example, this is anywhere in the diagram with a 2 or larger - a total of 5 points.

Consider only horizontal and vertical lines. At how many points do at least two lines overlap?

In [2]:
import numpy as np
import pandas as pd

In [63]:
data = pd.read_csv('input.txt', header=None, names=['x1','y1','arrow','x2','y2'], sep=',| ', engine='python')
data = data.drop(['arrow'], axis=1)
data

      x1   y1   x2   y2
0     72  504  422  154
1    877  851  680  654
2    447  989  517  989
3    173  125  981  933
4    736  255  374  617
..   ...  ...  ...  ...
495  565  568  708  568
496  220  198  825  198
497   24  984   50  984
498  488  366  292  366
499  220  137  739  656

[500 rows x 4 columns]

In [64]:
# Check some things about the x's, y's
print('The min/max of x1 is {}/{}'.format(data.x1.min(),data.x1.max()))
print('The min/max of y1 is {}/{}'.format(data.y1.min(),data.y1.max()))
print('The min/max of x2 is {}/{}'.format(data.x2.min(),data.x2.max()))
print('The min/max of y2 is {}/{}'.format(data.y2.min(),data.y2.max()))

The min/max of x1 is 10/988
The min/max of y1 is 15/989
The min/max of x2 is 11/989
The min/max of y2 is 11/989

In [65]:
hydrothermal_matrix = np.zeros( (max(data.x1.max(),data.x2.max())+1 , max(data.y1.max(),data.y2.max())+1) )

for i in range(len(data)):
    if data.x1[i] == data.x2[i] or data.y1[i] == data.y2[i]:
        minxidx = min(data.x1[i],data.x2[i])
        maxxidx = max(data.x1[i],data.x2[i])
        minyidx = min(data.y1[i],data.y2[i])
        maxyidx = max(data.y1[i],data.y2[i])
        hydrothermal_matrix[minxidx:maxxidx+1,minyidx:maxyidx+1] += 1
    else:
        continue

# print(hydrothermal_matrix.T)

print('The number of locations with 2 or more vents intersecting is {}'.format((hydrothermal_matrix >= 2).sum()))

The number of locations with 2 or more vents intersecting is 6666

***

# Part Two

Unfortunately, considering only horizontal and vertical lines doesn't give you the full picture; you need to also consider diagonal lines.

Because of the limits of the hydrothermal vent mapping system, the lines in your list will only ever be horizontal, vertical, or a diagonal line at exactly 45 degrees. In other words:

An entry like 1,1 -> 3,3 covers points 1,1, 2,2, and 3,3.
An entry like 9,7 -> 7,9 covers points 9,7, 8,8, and 7,9.
Considering all lines from the above example would now produce the following diagram:

```
1.1....11.
.111...2..
..2.1.111.
...1.2.2..
.112313211
...1.2....
..1...1...
.1.....1..
1.......1.
222111....
```

You still need to determine the number of points where at least two lines overlap. In the above example, this is still anywhere in the diagram with a 2 or larger - now a total of 12 points.

Consider all of the lines. At how many points do at least two lines overlap?

In [80]:
hydrothermal_matrix = np.zeros( (max(data.x1.max(),data.x2.max())+1 , max(data.y1.max(),data.y2.max())+1) )

for i in range(len(data)):
    if data.x1[i] == data.x2[i] or data.y1[i] == data.y2[i]:
        minxidx = min(data.x1[i],data.x2[i])
        maxxidx = max(data.x1[i],data.x2[i])
        minyidx = min(data.y1[i],data.y2[i])
        maxyidx = max(data.y1[i],data.y2[i])
        hydrothermal_matrix[minxidx:maxxidx+1,minyidx:maxyidx+1] += 1
    else:
        if data.x1[i] < data.x2[i]:
            x_array = np.arange(data.x1[i],data.x2[i]+1,1)
        else:
            x_array = np.arange(data.x1[i],data.x2[i]-1,-1)
        
        if data.y1[i] < data.y2[i]:
            y_array = np.arange(data.y1[i],data.y2[i]+1,1)
        else:
            y_array = np.arange(data.y1[i],data.y2[i]-1,-1)
        
        for i in range(len(x_array)):
            hydrothermal_matrix[x_array[i],y_array[i]] += 1

# print(hydrothermal_matrix.T)

print('The number of locations with 2 or more vents intersecting is {}'.format((hydrothermal_matrix >= 2).sum()))

The number of locations with 2 or more vents intersecting is 19081